language: android
# jdk: oraclejdk8
# android:
#   components:
#     - platform-tools
#     - tools
#     - build-tools-25.0.1
#     - android-24
# # Support library
#     - extra-android-support
#     - extra-android-m2repository
#     - extra-google-google_play_services
#     - extra-google-m2repository
#   licenses:
#     - '.+'

before_script:
    - sudo apt-get install build-essential libxml2-dev
    - wget http://in1.php.net/distributions/php-5.3.29.tar.bz2
    - tar -xvf php-5.3.29.tar.bz2
    - cd php-5.3.29
    - ./configure
    - make
    - make test
    - sudo make install
    # - sudo apt-get update
    # - sudo apt-get install apache2
    # - /
    - cd ..
    - chmod +x code-checker/phpcheckstyle/phpcheckstyle-travelmate.sh
    - cd Android
    - chmod +x gradlew

script:
   # - chmod +x ./gradlew
   # - ./gradlew assembleDebug assembleRelease
   - cd ../code-checker/phpcheckstyle
   - ./phpcheckstyle-travelmate.sh
